[package]
name = "lox-interpreter"
version = "0.1.0"
authors = ["Rishabh Chawla <rishabh31121999@gmail.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
thiserror = "1.0.38"
unicode-segmentation = "1.12.0"
